### <BOARD>
### Get all List

GET http://localhost:3000/boards

### Get List by id

GET http://localhost:3000/boards/2

### Create a new board

POST http://localhost:3000/boards
Content-Type: application/json; charset=UTF-8

{
  "title": "제목",
  "description": "안녕하세요22"
}

### Delete a board (by id)

DELETE http://localhost:3000/boards

### Update board status 

PATCH  http://localhost:3000/boards/유효한id값/status
Content-Type: application/json; charset=UTF-8

{
  "status": "PUBLIC"
}

////////////////////////////////////////////////////////////////

### AUTH

### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json; charset=UTF-8

{
  "username": "루미",
  "password": "1212",
}