### get all boards list
GET http://localhost:3000/boards

### get board by id
GET http://localhost:3000/boards/15

### create a new board
POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "board 6",
  "content": "board 6 입니다"
}

### delete a board by id
Delete http://localhost:3000/boards/111
